# update symbol link /srv/itranswarp -> /srv/itranswarp-{{ timestamp }}

---

- name: remove old symbol link /srv/itranswarp
  file:
    path: /srv/itranswarp
    state: absent

- name: create symbol link /srv/itranswarp -> /srv/itranswarp-{{ timestamp }}
  file:
    src: /srv/itranswarp-{{ timestamp }}
    dest: /srv/itranswarp
    state: link

- name: remove old deployed targets from /srv/itranswarp-*
  shell: "ls -td -1 itranswarp-* | tail -n +11"
  args:
    chdir: /srv/
  register: to_be_deleted

- name: will remove old deployed targets
  debug: msg="{{ item }}"
  with_items: "{{ to_be_deleted.stdout_lines }}"

- name: actually remove old deployed jars
  file:
    name: /srv/{{ item }}
    state: absent
  with_items: "{{ to_be_deleted.stdout_lines }}"
