# deploy jar file

---

- name: init app dir /srv/itranswarp-{{ timestamp }}
  file:
    path: /srv/itranswarp-{{ timestamp }}
    state: directory

- name: copy itranswarp.jar
  copy:
    src: ../release/itranswarp.jar
    dest: /srv/itranswarp-{{ timestamp }}/
