#
# Deploy itranswarp
# For Ubuntu Server 18.04 ONLY!
#

---

- hosts: itranswarp
  serial: 1
  become: yes
  become_user: root
  become_method: sudo
  vars_files:
    - environments/{{ profile }}/vars.yml
  roles:
    - { role: init_vars }

    - { role: install_jdk }
    - { role: install_nginx }
    - { role: install_supervisor }

    - { role: deploy_jar }
    - { role: deploy_source }

    - { role: gen_nginx_conf }
    - { role: gen_supervisor_conf }

    - { role: update_symbol_link }

    - { role: reload_supervisor }
    - { role: reload_nginx }
